theme: jekyll-theme-architect

title: "Prof. Goble"
description: "A collection of courses taught and personal work"

hide_first_title: true
show_downloads: false
buttons:
  zip_hide: true
  tar_hide: true
  github_hide: true

github:
  is_project_page: false
